version: '3'

services:
  ssserver-libev:
    build: ./ssserver
    container_name: ssserver-libev
    restart: always
    # ports: # 映射端口，如果需要让其他机器访问，请取消注释
    #   - '8388:8388/udp'
    #   - '8388:8388/tcp'
    environment:
      - SERVER=0.0.0.0
      - SERVER_PORT=8388
      - PASSWORD=Password
      - TIMEOUT=300
      - METHOD=aes-256-gcm
      - DNS_ADDRS=114.114.114.114,8.8.8.8
  # sslocal-libev:
  #   build: ./sslocal
  #   container_name: sslocal-libev
  #   restart: always
  #   ports:
  #     - '1080:1080/udp'
  #     - '1080:1080/tcp'
  #   environment:
  #     - SERVER=ssserver-libev
  #     - SERVER_PORT=8388
  #     - LOCAL_ADDRESS=0.0.0.0
  #     - LOCAL_PORT=1080
  #     - PASSWORD=Password
  #     - TIMEOUT=300
  #     - METHOD=aes-256-gcm
  # ssserver-manager-libev:
  #   build: ./ssserver-manager
  #   container_name: ssserver-manager-libev
  #   restart: always
  #   volumes:
  #     - ./manager.server.ssconfig.json:/.ssconfig.json:ro
  #   ports:
  #     # - "8388:8388/udp"   # ss-server 代理端口
  #     # - "8388:8388/tcp"   # ss-server 代理端口
  #     - "6000:6000"   # 管理界面端口
  sslocal-manager-libev:
    build: ./sslocal-manager
    container_name: sslocal-manager-libev
    restart: always
    volumes:
      - ./.ssconfig.json:/.ssconfig.json:ro
    ports:
      - "1080:1080/udp"   # ss-local 代理端口
      - "1080:1080/tcp"   # ss-local 代理端口
      - "5000:5000"   # 管理界面端口
    
# networks: # 网络配置，需要使用 IPv6 时取消注释
#   default:
#     enable_ipv6: true
