version: '3'

services:
  ss-manager:
    build: .
    container_name: ss-manager
    restart: always
    volumes:
      - ./.ssconfig.json:/.ssconfig.json:ro
    ports:
      - "1080:1080"   # ss-local 代理端口
      - "5000:5000"   # 管理界面端口
