version: '3'

services:
  sslocal-libev:
    image: petermatthew/sslocal-libev
    container_name: sslocal-libev
    restart: always
    ports:
      - '1080:1080/udp'
      - '1080:1080/tcp'
    environment:
      - SERVER=ss.example.com
      - SERVER_PORT=8388
      - LOCAL_ADDRESS=0.0.0.0
      - LOCAL_PORT=1080
      - PASSWORD=Password
      - TIMEOUT=300
      - METHOD=aes-256-gcm
