version: '3'

services:
  ssserver-libev:
    build: .
    container_name: ssserver-libev
    restart: always
    ports:
      - '8388:8388/udp'
      - '8388:8388/tcp'
    environment:
      - SERVER=0.0.0.0
      - SERVER_PORT=8388
      - PASSWORD=Password
      - TIMEOUT=300
      - METHOD=aes-256-gcm
      - DNS_ADDRS=114.114.114.114,8.8.8.8
    
# networks: # 网络配置，需要使用 IPv6 时取消注释
#   default:
#     enable_ipv6: true
